version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT}
      DB_HOST: postgres_db
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres_db
    networks:
      - nest_auth_project_net

  postgres_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      PGPORT: ${DB_PORT}
      POSTGRES_TIMEZONE: "Asia/Tashkent"
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - nest_auth_project_db:/var/lib/postgresql/data
    networks:
      - nest_auth_project_net

volumes:
  nest_auth_project_db:
    driver: local

networks:
  nest_auth_project_net:
    driver: bridge